/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleTipoProduto;
import control.MetodosPadrao;
import dao.Conecta_Banco;
import dao.Conecta_Tabela;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import model.ModeloTipoProduto;

/**
 *
 * @author muril
 */
public class CadastroTipoProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTipoProdutos
     */
    public CadastroTipoProdutos() {
        initComponents();
        preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
        jButtonEditar.setEnabled(false);
        jButtonInativar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTipo = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonInativar = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTipoProduto = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrar Tipo de Produtos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Coringa.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Tipo de Produtos");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCoringa.png"))); // NOI18N
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Tipo");

        jTextFieldTipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTipoKeyPressed(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(0, 168, 82));
        jButtonCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(68, 68, 66));
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonInativar.setBackground(new java.awt.Color(156, 32, 36));
        jButtonInativar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInativar.setText("Inativar");
        jButtonInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarActionPerformed(evt);
            }
        });

        jTextField6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton5.setBackground(new java.awt.Color(68, 68, 66));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTableTipoProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableTipoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTipoProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTipoProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipo))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonInativar, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonInativar)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       cadastrar();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTableTipoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTipoProdutoMouseClicked
        jTextFieldTipo.setText(jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 0)+"");
        jButtonCadastrar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonInativar.setEnabled(true);
        jTextFieldTipo.requestFocus();

        String status = jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 1)+"";
        
        if(status.equals("ATIVO"))
        {
            jButtonInativar.setText("INATIVAR");
            jButtonInativar.setBackground(new java.awt.Color(156,32,36));
        }
        else
        {
            jButtonInativar.setText("ATIVAR");
            jButtonInativar.setBackground(new java.awt.Color(0,168,82));
        }
        
    }//GEN-LAST:event_jTableTipoProdutoMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
       String produto= jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 0)+"";
       String id = jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 2)+"";
       
       int opc = JOptionPane.showConfirmDialog(null,"Deseja realmente alterar o produto "+produto+" ?");
       if(opc==JOptionPane.YES_OPTION)
       {
           ModeloTipoProduto modeloTipoProduto = new ModeloTipoProduto();
           modeloTipoProduto.setId(Integer.parseInt(id));
           modeloTipoProduto.setNm_tipo(jTextFieldTipo.getText());
           ControleTipoProduto controleTipoProduto = new ControleTipoProduto();
           controleTipoProduto.alterarTipoProduto(modeloTipoProduto);
           jTextFieldTipo.setText("");
           preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
           jButtonEditar.setEnabled(false);
           jButtonInativar.setEnabled(false);
           jButtonCadastrar.setEnabled(true);
       }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarActionPerformed
      String texto = jButtonInativar.getText();
      String ds_status="";
      
      if(texto.equals("ATIVAR"))
      {
          ds_status = "A";
      }
      else
      {
          ds_status = "I";
      }
      
      String produto= jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 0)+"";
      String id = jTableTipoProduto.getValueAt(jTableTipoProduto.getSelectedRow(), 2)+"";
      
      int opc = JOptionPane.showConfirmDialog(null,"Deseja realmente "+texto+" o produto "+produto+" ?");
      
       if(opc==JOptionPane.YES_OPTION)
       {
           ModeloTipoProduto modeloTipoProduto = new ModeloTipoProduto();
           modeloTipoProduto.setId(Integer.parseInt(id));
           modeloTipoProduto.setDs_status(ds_status);
           ControleTipoProduto controleTipoProduto = new ControleTipoProduto();
           controleTipoProduto.ativarInativarTipo(modeloTipoProduto);
           jTextFieldTipo.setText("");
           preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
           jButtonEditar.setEnabled(false);
           jButtonInativar.setEnabled(false);
           jButtonCadastrar.setEnabled(true);
       }
    }//GEN-LAST:event_jButtonInativarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     if(jTextField6.getText().isEmpty())
     {
         preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
         jButtonEditar.setEnabled(false);
           jButtonInativar.setEnabled(false);
           jButtonCadastrar.setEnabled(true);
     }
     else
     {
         String pesquisa = jTextField6.getText();
         
         preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO WHERE NM_TIPO LIKE '%"+pesquisa+"%' ORDER BY NM_TIPO;");
         jButtonEditar.setEnabled(false);
         jButtonInativar.setEnabled(false);
         jButtonCadastrar.setEnabled(true);
         
     }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTipoKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER && jButtonCadastrar.isEnabled()==true)
       {
            if(!jTextFieldTipo.getText().isEmpty())
            {
                ModeloTipoProduto tipoProduto = new ModeloTipoProduto();
                tipoProduto.setNm_tipo(jTextFieldTipo.getText());
                tipoProduto.setDs_status("A");
                ControleTipoProduto controle = new ControleTipoProduto();
                controle.gravarTipoProduto(tipoProduto);
                preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
            }
            else
            {
                MetodosPadrao metodo = new MetodosPadrao();
                metodo.validaCampo(jTextFieldTipo,"Tipo produto");
            }
       }
    }//GEN-LAST:event_jTextFieldTipoKeyPressed

    void cadastrar()
    {
         if(!jTextFieldTipo.getText().isEmpty())
        {
            ModeloTipoProduto tipoProduto = new ModeloTipoProduto();
            tipoProduto.setNm_tipo(jTextFieldTipo.getText());
            tipoProduto.setDs_status("A");
            ControleTipoProduto controle = new ControleTipoProduto();
            controle.gravarTipoProduto(tipoProduto);
            preencherTabela("SELECT ID, NM_TIPO, DS_STATUS FROM TIPO_PRODUTO ORDER BY NM_TIPO;");
            
        }
        else
        {
            MetodosPadrao metodo = new MetodosPadrao();
            metodo.validaCampo(jTextFieldTipo,"Tipo produto");
        }
        limparCampos();
    }
    
    void limparCampos()
    {
        jTextField6.requestFocus();
        jTextFieldTipo.setText("");
            jTextField6.setText("");
            jTextFieldTipo.requestFocus();
    }
    public void preencherTabela(String SQL) 
    {

       //MUDANDO A FONTE DO CABEÇALHO
       JTableHeader cabecalho = jTableTipoProduto.getTableHeader();
       cabecalho.setFont(new java.awt.Font("Arial", 1, 12));

       ArrayList dados = new ArrayList();

       Conecta_Banco conecta = new Conecta_Banco();
       conecta.conexao();

       String[] colunas = new String[]{"TIPO","STATUS","ID"};

       conecta.executaSQL(SQL);
       try {
           conecta.rs.first();
           do {
               String status = conecta.rs.getString("DS_STATUS");

               
                if(status.equals("A"))                
                {
                    status="ATIVO";
                }
                else
                {
                    status="INATIVO";
                }
              dados.add(new Object[]{conecta.rs.getString("NM_TIPO").toUpperCase(),                   
              status,conecta.rs.getInt("id")});

           } while (conecta.rs.next());
       } catch (SQLException ex) {

           JOptionPane.showMessageDialog(null,"Nenhum dado Encontrado!");
           System.out.println(ex);

       }

       jTableTipoProduto.getTableHeader().setReorderingAllowed(false);
       jTableTipoProduto.setAutoResizeMode(jTableTipoProduto.AUTO_RESIZE_OFF);
       jTableTipoProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

       JTableHeader header =  jTableTipoProduto.getTableHeader();
       DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
       centralizado.setHorizontalAlignment(SwingConstants.CENTER);

       Conecta_Tabela ct = new Conecta_Tabela(dados, colunas);
       jTableTipoProduto.setModel(ct);



       jTableTipoProduto.getColumnModel().getColumn(0).setPreferredWidth(375);
       jTableTipoProduto.getColumnModel().getColumn(0).setResizable(true);

       jTableTipoProduto.getColumnModel().getColumn(1).setPreferredWidth(375);
       jTableTipoProduto.getColumnModel().getColumn(1).setResizable(true);

       jTableTipoProduto.getColumnModel().getColumn(2).setPreferredWidth(375);
       jTableTipoProduto.getColumnModel().getColumn(2).setResizable(true);

       //Ocultando a Coluna ID
       jTableTipoProduto.getColumnModel().getColumn(2).setMinWidth(0);
       jTableTipoProduto.getColumnModel().getColumn(2).setMaxWidth(0);

       jTableTipoProduto.getTableHeader().setReorderingAllowed(false);
       jTableTipoProduto.setAutoResizeMode(jTableTipoProduto.AUTO_RESIZE_OFF);
       jTableTipoProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonInativar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTipoProduto;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldTipo;
    // End of variables declaration//GEN-END:variables
}
