/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleUsuario;
import control.MetodosPadrao;
import dao.Conecta_Banco;
import dao.Conecta_Tabela;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import model.ModeloUsuario;

/**
 *
 * @author muril
 */
public class CadastroFuncionarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroProdutos
     */
    MetodosPadrao metodo = new MetodosPadrao();
    
    public CadastroFuncionarios() {
        initComponents();
        buscaMatricula();
        preencherTabela("SELECT NM_USUARIO, ID_USUARIO, DS_MATRICULA,"
        + " DS_STATUS FROM USUARIOS");
        
    }

    String usuario="";
    public void passaDados(String user)
    {
        usuario=user;
    }
    
    void buscaMatricula()
    {
        int matricula = metodo.buscaUltimaMatricula();
              
        if(matricula<9)
        {
            jTextFieldMatricula.setText("000"+matricula);
        }
        else if(matricula<99)
        {
            jTextFieldMatricula.setText("00"+matricula);
        }
        else if(matricula<999)
        {
            jTextFieldMatricula.setText("0"+matricula);
        }
        else
        {
            jTextFieldMatricula.setText(matricula+"");
        }
            
    }
    
    public boolean validaCampos()
    {
        String senha = jPasswordFieldSenha.getText();
        String senhaConfirmar = jPasswordFieldConfirmaSenha.getText();
        
       
        if(jTextFieldNome.getText().isEmpty() 
            || jTextFieldUsuario.getText().isEmpty() ||
            (!senha.equals(senhaConfirmar)))
        {
            metodo.validaCampo(jTextFieldNome,"Nome");
            metodo.validaCampo(jTextFieldUsuario,"Usuário");
            metodo.validaCampoSenha(jPasswordFieldSenha,"Senha");
            metodo.validaCampoSenha(jPasswordFieldConfirmaSenha,"Confirmar Senha");
            
            if(!senha.equals(senhaConfirmar))
            {
                 JOptionPane.showMessageDialog(null,
                "Os Campos de senha estão diferentes","Erro:",JOptionPane.ERROR_MESSAGE);
                 jPasswordFieldSenha.setText("");
                 jPasswordFieldConfirmaSenha.setText("");
                 jPasswordFieldSenha.requestFocus();
            }
            
            if(jPasswordFieldConfirmaSenha.getText().isEmpty())
            {
                jPasswordFieldConfirmaSenha.requestFocus();
            }
            if(jTextFieldUsuario.getText().isEmpty())
            {
                jTextFieldUsuario.requestFocus();
            }
            if(jPasswordFieldSenha.getText().isEmpty())
            {
                jPasswordFieldSenha.requestFocus();
            }
            if(jTextFieldNome.getText().isEmpty())
            {
                jTextFieldNome.requestFocus();
            }
           
            return false;
        }
        else
        {
            return true;
        }
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javaSoundAudioDeviceFactory1 = new javazoom.jl.player.JavaSoundAudioDeviceFactory();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonInativar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jPasswordFieldConfirmaSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrar Funcionários");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Coringa.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Funcionários");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCoringa.png"))); // NOI18N
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Matrícula:");

        jTextFieldMatricula.setEditable(false);
        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Senha:");

        jButtonCadastrar.setBackground(new java.awt.Color(0, 168, 82));
        jButtonCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(68, 68, 66));
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonInativar.setBackground(new java.awt.Color(156, 32, 36));
        jButtonInativar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInativar.setText("Inativar");
        jButtonInativar.setEnabled(false);
        jButtonInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jButton5.setBackground(new java.awt.Color(68, 68, 66));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFuncionarios);

        jPasswordFieldSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldSenhaFocusLost(evt);
            }
        });

        jPasswordFieldConfirmaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordFieldConfirmaSenhaFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Confirmar Senha:");

        jTextFieldUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarioFocusLost(evt);
            }
        });
        jTextFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsuarioMouseClicked(evt);
            }
        });
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Usuário:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonInativar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonInativar)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
    cadastrar();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
       metodo.desfocaCampo(jTextFieldNome);
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioFocusLost
       metodo.desfocaCampo(jTextFieldUsuario);
    }//GEN-LAST:event_jTextFieldUsuarioFocusLost

    private void jPasswordFieldSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaFocusLost
        metodo.desfocaCampoSenha(jPasswordFieldSenha);
    }//GEN-LAST:event_jPasswordFieldSenhaFocusLost

    private void jPasswordFieldConfirmaSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmaSenhaFocusLost
        metodo.desfocaCampoSenha(jPasswordFieldConfirmaSenha);
    }//GEN-LAST:event_jPasswordFieldConfirmaSenhaFocusLost

    private void jTableFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFuncionariosMouseClicked
        jButtonEditar.setEnabled(true);
        jButtonInativar.setEnabled(true);
        jButtonCadastrar.setEnabled(false);
        
        jTextFieldNome.setText(jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 0)+"");
        jTextFieldUsuario.setText(jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 1)+"");
        jTextFieldMatricula.setText(jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 2)+"");
        
        String status= jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 3)+"";
        
        if(status.equals("INATIVO"))
        {
            jButtonInativar.setText("ATIVAR");
            jButtonInativar.setBackground(new java.awt.Color(0, 168, 82));
        }
        else
        {
            jButtonInativar.setText("INATIVAR");
            jButtonInativar.setBackground(new java.awt.Color(156,32,36));
        }
        
        
        jTextFieldUsuario.setEditable(false);
        jPasswordFieldSenha.requestFocus();
    }//GEN-LAST:event_jTableFuncionariosMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if(validaCampos() == true)
        {
            ModeloUsuario modeloUsuario = new ModeloUsuario();
            modeloUsuario.setNm_usuario(jTextFieldNome.getText());
            modeloUsuario.setDs_senha(jPasswordFieldSenha.getText());
            modeloUsuario.setId_usuario(jTextFieldUsuario.getText());
            modeloUsuario.setIn_alterar_senha("S");
            ControleUsuario controle = new ControleUsuario();
            controle.alterarUsuario(modeloUsuario);
            limpaCampos();
            preencherTabela("SELECT NM_USUARIO, ID_USUARIO, DS_MATRICULA, DS_STATUS FROM USUARIOS");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarActionPerformed
        ModeloUsuario modeloUsuario = new ModeloUsuario();
        if(jButtonInativar.getText().equals("ATIVAR"))
        {
            modeloUsuario.setDs_status("A");
        }
        else
        {
            modeloUsuario.setDs_status("I");
        }
        
        modeloUsuario.setId_usuario(jTextFieldUsuario.getText());
        ControleUsuario controleUsuario = new ControleUsuario();
        controleUsuario.ativaInativaUsuario(modeloUsuario);
        limpaCampos();
        preencherTabela("SELECT NM_USUARIO, ID_USUARIO, DS_MATRICULA, DS_STATUS FROM USUARIOS");
    }//GEN-LAST:event_jButtonInativarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        if(jTextFieldPesquisar.getText().isEmpty())
        {
            metodo.validaCampo(jTextFieldPesquisar,"Pesquisa");
        }
        else
        {
            Integer matricula =null;
            String nome= jTextFieldPesquisar.getText();
            try
            {
                matricula = Integer.parseInt(jTextFieldPesquisar.getText());

            }
            catch (Exception ex)
            {
                matricula=null;
            }

            String sql="SELECT NM_USUARIO, ID_USUARIO, DS_MATRICULA, DS_STATUS FROM USUARIOS "
             + "WHERE NM_USUARIO LIKE '%"+nome+"%' OR DS_MATRICULA="+matricula;

            
             
            preencherTabela(sql);
            
            jTextFieldNome.setText("");
            jTextFieldMatricula.setText("");
            jTextFieldPesquisar.setText("");
            jTextFieldUsuario.setText("");
            jPasswordFieldSenha.setText("");
            jPasswordFieldConfirmaSenha.setText("");
        }
        
         metodo.desfocaCampo(jTextFieldPesquisar);
         jTextFieldPesquisar.setText("");
         jTextFieldPesquisar.requestFocus();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextFieldUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioMouseClicked
       
    }//GEN-LAST:event_jTextFieldUsuarioMouseClicked

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
    if(jButtonCadastrar.isEnabled()==true && evt.getKeyCode() == KeyEvent.VK_ENTER)
    {
        cadastrar();
    }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    void cadastrar()
    {
        if(validaCampos() ==true)
       {
           System.out.println("entrou here");
           ModeloUsuario modelUsuario = new ModeloUsuario();
           modelUsuario.setDs_matricula(jTextFieldMatricula.getText());
           modelUsuario.setDs_senha(jPasswordFieldSenha.getText());
           modelUsuario.setId_usuario(jTextFieldUsuario.getText());
           modelUsuario.setNm_usuario(jTextFieldNome.getText());
           ControleUsuario controle_usuario = new ControleUsuario();
           controle_usuario.CadastrarUsuario(modelUsuario);
           
           int id= controle_usuario.buscaMaximoIdUsuario();
           controle_usuario.cadastrarAcesso(id);
           
           limpaCampos();
       }
    }
    void limpaCampos()
    {
        jTextFieldNome.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldUsuario.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmaSenha.setText("");
        jButtonEditar.setEnabled(false);
        jButtonInativar.setEnabled(false);
        jButtonCadastrar.setEnabled(true);
        jTextFieldNome.requestFocus();
        buscaMatricula();
        preencherTabela("SELECT NM_USUARIO, ID_USUARIO, DS_MATRICULA,"
        + " DS_STATUS FROM USUARIOS");
    }
    
    public void preencherTabela(String SQL) 
     {

        //MUDANDO A FONTE DO CABEÇALHO
        JTableHeader cabecalho = jTableFuncionarios.getTableHeader();
        cabecalho.setFont(new java.awt.Font("Arial", 1, 12));

        
        
    
        
        ArrayList dados = new ArrayList();

        Conecta_Banco conecta = new Conecta_Banco();
        conecta.conexao();

        String[] colunas = new String[]{"NOME","LOGIN","MATRICULA","STATUS"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
               String status=conecta.rs.getString("DS_STATUS");
               
               if(status.equals("A"))
               {
                   status ="ATIVO";
               }
               else
               {
                   status="INATIVO";
               }
               dados.add(new Object[]{conecta.rs.getString("NM_USUARIO").toUpperCase(),
               conecta.rs.getString("ID_USUARIO").toUpperCase(),conecta.rs.getInt("DS_MATRICULA"),
               status});

            } while (conecta.rs.next());
        } catch (SQLException ex) {
           
            JOptionPane.showMessageDialog(null,"Nenhum dado Encontrado!");
            //System.out.println(ex);
             
        }
        
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        JTableHeader header =  jTableFuncionarios.getTableHeader();
        DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        Conecta_Tabela ct = new Conecta_Tabela(dados, colunas);
        jTableFuncionarios.setModel(ct);

        

        jTableFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(400);
        jTableFuncionarios.getColumnModel().getColumn(0).setResizable(true);
        
        jTableFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTableFuncionarios.getColumnModel().getColumn(1).setResizable(true);
        
        jTableFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableFuncionarios.getColumnModel().getColumn(2).setResizable(true);
        
        jTableFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableFuncionarios.getColumnModel().getColumn(3).setResizable(true);
       
        
        jTableFuncionarios.getTableHeader().setReorderingAllowed(false);
        jTableFuncionarios.setAutoResizeMode(jTableFuncionarios.AUTO_RESIZE_OFF);
        jTableFuncionarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonInativar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldUsuario;
    private javazoom.jl.player.JavaSoundAudioDeviceFactory javaSoundAudioDeviceFactory1;
    // End of variables declaration//GEN-END:variables
}
