/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ControleFornecedor;
import control.MetodosPadrao;
import dao.Conecta_Banco;
import dao.Conecta_Tabela;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import model.ModeloFornecedor;

/**
 *
 * @author muril
 */
public class CadastroFornecedores extends javax.swing.JInternalFrame {

    
    /**
     * Creates new form CadastroFornecedores
     */
    public CadastroFornecedores() {
        initComponents();
        preencherTabela("SELECT NM_FORNECEDOR, NR_CNPJ, NR_TELEFONE, ID_EMAIL FROM FORNECEDORES WHERE DS_STATUS='A';");
    }
    
    String id="";
    public void passaDados(String usuario)
    {
        
        id= usuario;
        
    }

    MetodosPadrao metodo = new MetodosPadrao();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTelefone = new javax.swing.JTextField();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonInativar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Cadastrar Fornecedores");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Coringa.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(729, 629));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastrar Fornecedores");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCoringa.png"))); // NOI18N
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jTextFieldNome.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNomeFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("CNPJ:");

        jTextFieldTelefone.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefoneFocusLost(evt);
            }
        });

        jButtonCadastrar.setBackground(new java.awt.Color(0, 168, 82));
        jButtonCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(68, 68, 66));
        jButtonEditar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonInativar.setBackground(new java.awt.Color(156, 32, 36));
        jButtonInativar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInativar.setText("Inativar");
        jButtonInativar.setEnabled(false);
        jButtonInativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInativarActionPerformed(evt);
            }
        });

        jTextFieldPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
        });

        jButtonPesquisar.setBackground(new java.awt.Color(68, 68, 66));
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jTableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFornecedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFornecedores);

        try {
            jFormattedTextFieldCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCnpj.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jFormattedTextFieldCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldCnpjFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Telefone:");

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("E-mail:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Nome ou CNPJ:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInativar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNome)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTelefone))
                            .addComponent(jTextFieldEmail))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar)
                        .addGap(8, 8, 8)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel9)
                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonInativar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
    cadastrar();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusLost
        metodo.desfocaCampo(jTextFieldNome);
    }//GEN-LAST:event_jTextFieldNomeFocusLost

    private void jTextFieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFocusGained

    private void jFormattedTextFieldCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCnpjFocusLost
       metodo.desfocaCampoFormatado(jFormattedTextFieldCnpj);
    }//GEN-LAST:event_jFormattedTextFieldCnpjFocusLost

    private void jTextFieldTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneFocusLost
       metodo.desfocaCampo(jTextFieldTelefone);
    }//GEN-LAST:event_jTextFieldTelefoneFocusLost

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
       metodo.desfocaCampo(jTextFieldEmail);
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTableFornecedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFornecedoresMouseClicked
        jButtonCadastrar.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonInativar.setEnabled(true);
        jFormattedTextFieldCnpj.setEditable(false);
        
        jTextFieldNome.setText(jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 0)+"");
        jTextFieldTelefone.setText(jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 2)+"");
        jFormattedTextFieldCnpj.setText(jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 1)+"");
        jTextFieldEmail.setText(jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 3)+"");
        
        
    }//GEN-LAST:event_jTableFornecedoresMouseClicked

    private void jButtonInativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInativarActionPerformed
       String cnpj = jFormattedTextFieldCnpj.getText();
       String nome =  "" + jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 0);
       int id_fornecedor = metodo.buscaIdFornecedor(cnpj);
       
       ControleFornecedor controle = new ControleFornecedor();
       controle.inativaFornecedor(id_fornecedor,nome);
       preencherTabela("SELECT NM_FORNECEDOR, NR_CNPJ, NR_TELEFONE, ID_EMAIL FROM FORNECEDORES WHERE DS_STATUS='A';");
       limpaCampos();
       jButtonCadastrar.setEnabled(true);
    }//GEN-LAST:event_jButtonInativarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
    editar();       
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
    pesquisarFornecedor();
         
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
       if(evt.getKeyCode() == evt.VK_ENTER && jButtonCadastrar.isEnabled()==true)
       {
           cadastrar();
       }
       else if(evt.getKeyCode() == evt.VK_ENTER && jButtonCadastrar.isEnabled()==false)
       {
           editar();
       }
    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_ENTER)
      {
          pesquisarFornecedor();
      }
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    //01.679.569/0001-98
    boolean validaCampos()
    {
        int cnpj = jFormattedTextFieldCnpj.getText().trim().length();
        
        if(jTextFieldNome.getText().isEmpty() || cnpj <18 || jTextFieldTelefone.getText().isEmpty()
        || jTextFieldEmail.getText().isEmpty())
        {
                metodo.validaCampo(jTextFieldEmail,"E-mail");
                metodo.validaCampo(jTextFieldTelefone,"Telefone");
                metodo.validaCampoFormatado(jFormattedTextFieldCnpj,"CNPJ",18);
                metodo.validaCampo(jTextFieldNome,"Nome");
                
           
            return false;
        }
        else
        {
            return true;
        }
    }
    
    void limpaCampos()
    {
        jTextFieldNome.setText("");
        jTextFieldTelefone.setText("");
        jTextFieldEmail.setText("");
        jFormattedTextFieldCnpj.setText("");
        jTextFieldNome.requestFocus();
        jButtonEditar.setEnabled(false);
        jButtonInativar.setEnabled(false);
        jFormattedTextFieldCnpj.setEditable(true);
        preencherTabela("SELECT NM_FORNECEDOR, NR_CNPJ, NR_TELEFONE, ID_EMAIL FROM FORNECEDORES WHERE DS_STATUS='A';");
    }
    
    void pesquisarFornecedor()
    {
        
        if(jTextFieldPesquisar.getText().isEmpty())
        {
            limpaCampos();
        }
        else            
        {
            String dado = jTextFieldPesquisar.getText();
            
            preencherTabela("SELECT NM_FORNECEDOR, NR_CNPJ, NR_TELEFONE, ID_EMAIL "
            + "FROM FORNECEDORES WHERE (NM_FORNECEDOR LIKE '%"+dado+"%' OR NR_CNPJ "
            + "LIKE '%"+dado+"%') AND DS_STATUS='A';");
            
            
        }
        
    }
    
    void cadastrar()
    {
        if(validaCampos() ==true)
        {
            ModeloFornecedor modeloFornecedor = new ModeloFornecedor();
            modeloFornecedor.setNm_fornecedor(jTextFieldNome.getText());
            modeloFornecedor.setDs_status("A");
            modeloFornecedor.setNr_telefone(jTextFieldTelefone.getText());
            modeloFornecedor.setNr_cnpj(jFormattedTextFieldCnpj.getText());
            modeloFornecedor.setId_usuario(id);
            modeloFornecedor.setId_email(jTextFieldEmail.getText());
            ControleFornecedor controleFornecedor = new ControleFornecedor();
            controleFornecedor.cadastrarFornecedores(modeloFornecedor);
            limpaCampos();
        }
    }
    
    void editar()
    {
        if(validaCampos() ==true)
       {
            String cnpj = jFormattedTextFieldCnpj.getText();
            String nome =  "" + jTableFornecedores.getValueAt(jTableFornecedores.getSelectedRow(), 0);
            
            int id_fornecedor = metodo.buscaIdFornecedor(cnpj);
            
            ModeloFornecedor modeloFornecedor = new ModeloFornecedor();
            modeloFornecedor.setNm_fornecedor(jTextFieldNome.getText());
            modeloFornecedor.setNr_telefone(jTextFieldTelefone.getText());
            modeloFornecedor.setId_email(jTextFieldEmail.getText());
            modeloFornecedor.setId(id_fornecedor);
            

            ControleFornecedor controle = new ControleFornecedor();
            controle.editaFornecedor(modeloFornecedor,nome);
            preencherTabela("SELECT NM_FORNECEDOR, NR_CNPJ, NR_TELEFONE, ID_EMAIL FROM FORNECEDORES WHERE DS_STATUS='A';");
            limpaCampos();
            jButtonCadastrar.setEnabled(true);
       }
    }
    
     public void preencherTabela(String SQL) 
     {

        //MUDANDO A FONTE DO CABEÇALHO
        JTableHeader cabecalho = jTableFornecedores.getTableHeader();
        cabecalho.setFont(new java.awt.Font("Arial", 1, 12));

        
        
    
        
        ArrayList dados = new ArrayList();

        Conecta_Banco conecta = new Conecta_Banco();
        conecta.conexao();

        String[] colunas = new String[]{"NOME","CNPJ","TELEFONE","EMAIL"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do {
               dados.add(new Object[]{conecta.rs.getString("nm_fornecedor").toUpperCase(),
               conecta.rs.getString("nr_cnpj").toUpperCase(),conecta.rs.getString("nr_telefone").toUpperCase(),
               conecta.rs.getString("id_email").toUpperCase()});

            } while (conecta.rs.next());
        } catch (SQLException ex) {
           
            JOptionPane.showMessageDialog(null,"Nenhum dado Encontrado!");
            //System.out.println(ex);
             
        }
        
        jTableFornecedores.getTableHeader().setReorderingAllowed(false);
        jTableFornecedores.setAutoResizeMode(jTableFornecedores.AUTO_RESIZE_OFF);
        jTableFornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        JTableHeader header =  jTableFornecedores.getTableHeader();
        DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        Conecta_Tabela ct = new Conecta_Tabela(dados, colunas);
        jTableFornecedores.setModel(ct);

        

        jTableFornecedores.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTableFornecedores.getColumnModel().getColumn(0).setResizable(true);
        
        jTableFornecedores.getColumnModel().getColumn(1).setPreferredWidth(190);
        jTableFornecedores.getColumnModel().getColumn(1).setResizable(true);
        
        jTableFornecedores.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTableFornecedores.getColumnModel().getColumn(2).setResizable(true);
        
        jTableFornecedores.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTableFornecedores.getColumnModel().getColumn(3).setResizable(true);
       
        
        jTableFornecedores.getTableHeader().setReorderingAllowed(false);
        jTableFornecedores.setAutoResizeMode(jTableFornecedores.AUTO_RESIZE_OFF);
        jTableFornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonInativar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedores;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
