/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.MetodosPadrao;
import dao.Conecta_Banco;
import dao.Conecta_Tabela;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import jxl.write.WriteException;
import relatorios.RelatorioEstoqueExcel;

/**
 *
 * @author Murilo Santos
 */
public class RelatorioEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form RelatorioEstoque
     */
    public RelatorioEstoque() {
        initComponents();
        preencherTabela("SELECT PRD.NM_PRODUTO, ESTQ.ESTOQUE, "
        + "ESTQ.ESTOQUE_ABAIXO, PRD.VL_COMPRA, PRD.VL_VENDA FROM ESTOQUE "
        + "AS ESTQ JOIN PRODUTOS AS PRD ON  PRD.ID = ESTQ.ID_PRODUTO");
    }
    
    MetodosPadrao metodos = new MetodosPadrao();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigoBarras = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jComboBoxEstoqueAbaixo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonRelatorioExcel = new javax.swing.JButton();
        jTextFieldEstoqueInicial = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldEstoqueFinal = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Relatório de Estoque");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Coringa.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(34, 34, 34));

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Relatório de Estoque");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconeCoringa.png"))); // NOI18N
        jLabel8.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Código ou Nome do produto:");

        jTextFieldCodigoBarras.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTableVendas.setAutoCreateRowSorter(true);
        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVendas);

        jComboBoxEstoqueAbaixo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBoxEstoqueAbaixo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "Sim", "Não" }));
        jComboBoxEstoqueAbaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxEstoqueAbaixoMouseEntered(evt);
            }
        });
        jComboBoxEstoqueAbaixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstoqueAbaixoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Estoque Abaixo:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Estoque Inicial:");

        jButtonPesquisar.setBackground(new java.awt.Color(68, 68, 66));
        jButtonPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonRelatorioExcel.setBackground(new java.awt.Color(0, 168, 82));
        jButtonRelatorioExcel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRelatorioExcel.setText("Relatório Excel");
        jButtonRelatorioExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioExcelActionPerformed(evt);
            }
        });

        jTextFieldEstoqueInicial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Estoque Final:");

        jTextFieldEstoqueFinal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstoqueAbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstoqueInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEstoqueFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRelatorioExcel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxEstoqueAbaixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldEstoqueInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldEstoqueFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelatorioExcel)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEstoqueAbaixoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxEstoqueAbaixoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstoqueAbaixoMouseEntered

    private void jComboBoxEstoqueAbaixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstoqueAbaixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstoqueAbaixoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
    String codigoBarras="";
    String estoqueAbaixo="";
    String estoqueInicial = "";
    String estoqueFinal="";
    String nomeProduto ="";
    
    
    if(jComboBoxEstoqueAbaixo.getSelectedIndex()==0)
    {
        estoqueAbaixo="null";
    }
    else if(jComboBoxEstoqueAbaixo.getSelectedIndex()==1)
    {
        estoqueAbaixo="'S'";
    }
    else
    {
        estoqueAbaixo="'N'";
    }
    
    
    if(jTextFieldCodigoBarras.getText().isEmpty())
    {
        codigoBarras="null";
        nomeProduto="null";
    }
    else
    {
        codigoBarras = jTextFieldCodigoBarras.getText();
        
        try {
            System.out.println(codigoBarras.substring(0,1));
            
            int teste = Integer.parseInt(codigoBarras.substring(0,1));
            nomeProduto ="null";
            
        } catch (Exception e) {
            nomeProduto=jTextFieldCodigoBarras.getText();
            codigoBarras ="null";
        }
        
      
    }
    
    if(jTextFieldEstoqueInicial.getText().isEmpty())
    {
        estoqueInicial="null";
    }
    else
    {
        estoqueInicial = jTextFieldEstoqueInicial.getText();
    }
    
    if(jTextFieldEstoqueFinal.getText().isEmpty())
    {
        estoqueFinal="null";
    }
    else
    {
        estoqueFinal=jTextFieldEstoqueFinal.getText();
    }
    
    
    String sql="SELECT PRD.NM_PRODUTO, ESTQ.ESTOQUE, "
    + "ESTQ.ESTOQUE_ABAIXO, PRD.VL_COMPRA, PRD.VL_VENDA FROM ESTOQUE AS ESTQ JOIN PRODUTOS AS PRD ON PRD.ID = ESTQ.ID_PRODUTO\n" +
    "WHERE ("+codigoBarras+" IS NULL OR PRD.CD_BARRAS="+codigoBarras+") AND ("
    +estoqueAbaixo+" IS NULL OR "
    + "ESTQ.ESTOQUE_ABAIXO="+estoqueAbaixo+") AND ("+estoqueInicial+
    " IS NULL OR ESTQ.ESTOQUE >="+estoqueInicial+") \n" +
    "AND ("+estoqueFinal+" IS NULL OR ESTQ.ESTOQUE <="+estoqueFinal+") "
    + "AND ('"+nomeProduto+"' is null or PRD.NM_PRODUTO LIKE '%"+nomeProduto+"%' OR PRD.CD_BARRAS="+codigoBarras+") ;";
    
    sql = sql.replace("'null'","null");
        
    preencherTabela(sql);
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonRelatorioExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioExcelActionPerformed
    String codigoBarras="";
    String estoqueAbaixo="";
    String estoqueInicial = "";
    String estoqueFinal="";
    String nomeProduto ="";
    
    
    if(jComboBoxEstoqueAbaixo.getSelectedIndex()==0)
    {
        estoqueAbaixo="null";
    }
    else if(jComboBoxEstoqueAbaixo.getSelectedIndex()==1)
    {
        estoqueAbaixo="'S'";
    }
    else
    {
        estoqueAbaixo="'N'";
    }
    
    
    if(jTextFieldCodigoBarras.getText().isEmpty())
    {
        codigoBarras="null";
        nomeProduto="null";
    }
    else
    {
        codigoBarras = jTextFieldCodigoBarras.getText();
        
        try {
            System.out.println(codigoBarras.substring(0,1));
            
            int teste = Integer.parseInt(codigoBarras.substring(0,1));
            nomeProduto ="null";
            
        } catch (Exception e) {
            nomeProduto=jTextFieldCodigoBarras.getText();
            codigoBarras ="null";
        }
        
      
    }
    
    if(jTextFieldEstoqueInicial.getText().isEmpty())
    {
        estoqueInicial="null";
    }
    else
    {
        estoqueInicial = jTextFieldEstoqueInicial.getText();
    }
    
    if(jTextFieldEstoqueFinal.getText().isEmpty())
    {
        estoqueFinal="null";
    }
    else
    {
        estoqueFinal=jTextFieldEstoqueFinal.getText();
    }
        
    String sql="SELECT PRD.NM_PRODUTO, ESTQ.ESTOQUE, ESTQ.ESTOQUE_ABAIXO, "
    + "PRD.VL_COMPRA, PRD.VL_VENDA FROM ESTOQUE AS ESTQ JOIN PRODUTOS AS "
    + "PRD ON PRD.ID = ESTQ.ID_PRODUTO\n" +
    "WHERE ("+codigoBarras+" IS NULL OR PRD.CD_BARRAS="+codigoBarras+") AND ("
    +estoqueAbaixo+" IS NULL OR "
    + "ESTQ.ESTOQUE_ABAIXO="+estoqueAbaixo+") AND ("+estoqueInicial+
    " IS NULL OR ESTQ.ESTOQUE >="+estoqueInicial+") \n" +
    "AND ("+estoqueFinal+" IS NULL OR ESTQ.ESTOQUE <="+estoqueFinal+") "
    + "AND ('"+nomeProduto+"' is null or PRD.NM_PRODUTO LIKE '%"+nomeProduto+"%' OR PRD.CD_BARRAS="+codigoBarras+") ;";
    
    sql = sql.replace("'null'","null");
    
    System.out.println("SQL: "+sql);
    
    try 
    {
        RelatorioEstoqueExcel relatorio = new RelatorioEstoqueExcel();
        relatorio.gerarRelatorioEstoque(sql);
    } 
    catch (WriteException ex) 
    {
        JOptionPane.showMessageDialog(null,"ERRO AO GERAR RELATÓRIO: "+ex);       
    }
    
   
    }//GEN-LAST:event_jButtonRelatorioExcelActionPerformed

    public void preencherTabela(String SQL) 
    {               
        //System.out.println("SQL NECESSARIO:\n"+SQL);
        //MUDANDO A FONTE DO CABEÇALHO
        JTableHeader cabecalho = jTableVendas.getTableHeader();
        cabecalho.setFont(new java.awt.Font("Arial", 1, 12));

        ArrayList dados = new ArrayList();

        Conecta_Banco conecta = new Conecta_Banco();
        conecta.conexao();

        String[] colunas = new String[]{"NOME DO PRODUTO","ESTOQUE","ESTOQUE ABAIXO","VALOR DE COMPRA DO PRODUTO",
        "TOTAL EM PRODUTOS DISPONÍVEIS","VALOR DE VENDA DO PRODUTO","TOTAL DIPONÍVEL PARA VENDA DO PRODUTO"};

        conecta.executaSQL(SQL);
        try {
            conecta.rs.first();
            do 
            {
               
               int estoque = conecta.rs.getInt("ESTOQUE");
               float valorVenda=conecta.rs.getFloat("VL_VENDA");
               float valorCompra=conecta.rs.getFloat("VL_COMPRA");
               
               float totalVenda=0;
               float totalCompra=0;
               
               if(estoque>0)
               {
                   totalVenda = valorVenda*estoque;
                   totalCompra = valorCompra*estoque;
               }
                
                
               String valorVendaFinal  =  metodos.formataFloats(valorVenda);
               String valorCompraFinal =  metodos.formataFloats(valorCompra);
               String totalVendaFinal  =  metodos.formataFloats(totalVenda); 
               String totalCompraFinal =  metodos.formataFloats(totalCompra);
                
               String estoqueAbaixo = conecta.rs.getString("estoque_abaixo");
               
               if(estoqueAbaixo.equals("S"))
               {
                   estoqueAbaixo = "SIM";
               }
               else
               {
                   estoqueAbaixo = "NÃO";
               }
               dados.add(new Object[]{conecta.rs.getString("NM_PRODUTO").toUpperCase(),
               conecta.rs.getString("ESTOQUE").toUpperCase(),estoqueAbaixo,valorCompraFinal,
               totalCompraFinal,valorVendaFinal,totalVendaFinal
               });

            } while (conecta.rs.next());
        } catch (SQLException ex) {
           
            JOptionPane.showMessageDialog(null,"Nenhum dado Encontrado!");
            System.out.println(ex);
             
        }
        finally{
            conecta.desconecta();
        }
        
        jTableVendas.getTableHeader().setReorderingAllowed(false);
        jTableVendas.setAutoResizeMode(jTableVendas.AUTO_RESIZE_OFF);
        jTableVendas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        JTableHeader header =  jTableVendas.getTableHeader();
        DefaultTableCellRenderer centralizado = (DefaultTableCellRenderer) header.getDefaultRenderer();
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);

        Conecta_Tabela ct = new Conecta_Tabela(dados, colunas);
        jTableVendas.setModel(ct);

        jTableVendas.getColumnModel().getColumn(0).setPreferredWidth(300);
        jTableVendas.getColumnModel().getColumn(0).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableVendas.getColumnModel().getColumn(1).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(2).setPreferredWidth(150);
        jTableVendas.getColumnModel().getColumn(2).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(3).setPreferredWidth(250);
        jTableVendas.getColumnModel().getColumn(3).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(4).setPreferredWidth(250);
        jTableVendas.getColumnModel().getColumn(4).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTableVendas.getColumnModel().getColumn(5).setResizable(true);
        
        jTableVendas.getColumnModel().getColumn(6).setPreferredWidth(350);
        jTableVendas.getColumnModel().getColumn(6).setResizable(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRelatorioExcel;
    private javax.swing.JComboBox<String> jComboBoxEstoqueAbaixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextFieldCodigoBarras;
    private javax.swing.JTextField jTextFieldEstoqueFinal;
    private javax.swing.JTextField jTextFieldEstoqueInicial;
    // End of variables declaration//GEN-END:variables
}
